In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
# Load the dataset
data = pd.read_csv(r"C:\Users\sushu\OneDrive\Desktop\datasets\credit_risk_dataset.csv\credit_risk_dataset.csv")

# Display basic information about the dataset
print(data.info())
print(data.describe())
print(data.head())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  32581 non-null  int64  
 1   person_income               32581 non-null  int64  
 2   person_home_ownership       32581 non-null  object 
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object 
 5   loan_grade                  32581 non-null  object 
 6   loan_amnt                   32581 non-null  int64  
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64  
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object 
 11  cb_person_cred_hist_length  32581 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB
None
         person_age  perso

In [3]:
data.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [4]:
# Handle missing values
data = data.dropna()  

# Encode categorical variables
label_encoders = {}
for column in ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
    label_encoders[column] = le

# Standardize numerical features
scaler = StandardScaler()
data[['person_age', 'person_income', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']] = \
    scaler.fit_transform(data[['person_age', 'person_income', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']])


In [5]:
# Define features and target variable
X = data.drop(columns=['loan_status'])
y = data['loan_status']


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [7]:
# Train the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [8]:
# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.9296438547486033
Confusion Matrix:
[[4420   23]
 [ 380  905]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      4443
           1       0.98      0.70      0.82      1285

    accuracy                           0.93      5728
   macro avg       0.95      0.85      0.89      5728
weighted avg       0.93      0.93      0.93      5728



In [9]:

from imblearn.over_sampling import SMOTE

# Resample the training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Train the Random Forest model on the resampled data
model_resampled = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model_resampled.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_resampled = model_resampled.predict(X_test)

# Evaluate the model
accuracy_resampled = accuracy_score(y_test, y_pred_resampled)
conf_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
class_report_resampled = classification_report(y_test, y_pred_resampled)

print(f'Accuracy (Resampled): {accuracy_resampled}')
print('Confusion Matrix (Resampled):')
print(conf_matrix_resampled)
print('Classification Report (Resampled):')
print(class_report_resampled)


Accuracy (Resampled): 0.9205656424581006
Confusion Matrix (Resampled):
[[4316  127]
 [ 328  957]]
Classification Report (Resampled):
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      4443
           1       0.88      0.74      0.81      1285

    accuracy                           0.92      5728
   macro avg       0.91      0.86      0.88      5728
weighted avg       0.92      0.92      0.92      5728



In [10]:
# Resample the training data using SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)


In [13]:
# Train the Random Forest model on the resampled data
model_resampled = RandomForestClassifier(n_estimators=100, random_state=42)
model_resampled.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_resampled = model_resampled.predict(X_test)

# Evaluate the model
accuracy_resampled = accuracy_score(y_test, y_pred_resampled)
conf_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
class_report_resampled = classification_report(y_test, y_pred_resampled)

print(f'Accuracy (Resampled): {accuracy_resampled}')
print('Confusion Matrix (Resampled):')
print(conf_matrix_resampled)
print('Classification Report (Resampled):')
print(class_report_resampled)


Accuracy (Resampled): 0.9205656424581006
Confusion Matrix (Resampled):
[[4316  127]
 [ 328  957]]
Classification Report (Resampled):
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      4443
           1       0.88      0.74      0.81      1285

    accuracy                           0.92      5728
   macro avg       0.91      0.86      0.88      5728
weighted avg       0.92      0.92      0.92      5728



In [14]:
# Train the Random Forest model with adjusted class weights
model_weighted = RandomForestClassifier(n_estimators=100, random_state=42, class_weight={0: 1, 1: 3})
model_weighted.fit(X_train, y_train)

# Make predictions on the test set
y_pred_weighted = model_weighted.predict(X_test)

# Evaluate the model
accuracy_weighted = accuracy_score(y_test, y_pred_weighted)
conf_matrix_weighted = confusion_matrix(y_test, y_pred_weighted)
class_report_weighted = classification_report(y_test, y_pred_weighted)

print(f'Accuracy (Weighted): {accuracy_weighted}')
print('Confusion Matrix (Weighted):')
print(conf_matrix_weighted)
print('Classification Report (Weighted):')
print(class_report_weighted)


Accuracy (Weighted): 0.9299930167597765
Confusion Matrix (Weighted):
[[4428   15]
 [ 386  899]]
Classification Report (Weighted):
              precision    recall  f1-score   support

           0       0.92      1.00      0.96      4443
           1       0.98      0.70      0.82      1285

    accuracy                           0.93      5728
   macro avg       0.95      0.85      0.89      5728
weighted avg       0.93      0.93      0.93      5728

